
<td style="border:#FFFFFF solid 1px" width="28%" align="center" class="style3"><?=LANG_est_tools?></td>
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="14%" align="center"><?php if($_GET['id']!=$_SESSION['CASOACTUAL']){ ?><a href="index.php?id=<?=$_SESSION['CASOACTUAL'] ?>"><img src="../../images/common/documents.gif" title="<?=LANG_est_cont_alt ?>" width="24" height="24" border="0"></a><? }else{ ?><img src="../../images/common/documentsU.gif" width="24" height="24" border="0"><?php } ?></td>
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="15%" align="center"><?php if($_GET['o']!=2){ ?><a href="files.php?o=2"><img src="../../images/common/save.gif" title="<?=LANG_est_file_alt ?>" width="24" height="24" border="0"></a><? }else{ ?><img src="../../images/common/saveU.gif" width="24" height="24" border="0"><?php } ?></td>
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="15%" align="center"><?php if($_GET['o']!=3){ ?><a href="links.php?o=3"><img src="../../images/common/web_find.gif" title="<?=LANG_content_links ?>" width="24" height="24" border="0"></a><? }else{ ?><img src="../../images/common/web_findU.gif" width="24" height="24" border="0"><?php } ?></td>
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="15%" align="center"><?php if($_GET['o']!=4){ ?><a href="videos.php?o=4"><img src="../../images/common/vid.gif" title="<?=LANG_content_video ?>" width="24" height="24" border="0"></a><? }else{ ?><img src="../../images/common/vidU.gif" width="24" height="24" border="0"><?php } ?></td>
<!--mandar mensaje de consulta-->
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="15%" align="center"><a href="javascript:popup('../mensajes/responder_t.php','','400','700');"><img src="../../images/common/mail2.gif" title="<?php echo LANG_est_request ?>" width="24" height="24" border="0"></a></td>
<!---->
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="14%" align="center"><?php if($_GET['o']!=5){ ?><a href="eval.php?o=5"><img src="../../images/common/eval.gif" title="<?=LANG_est_eval_alt ?>" width="24" height="24" border="0"></a><? }else{ ?><img src="../../images/common/evalU.gif" width="24" height="24" border="0"><?php } ?></td>
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="15%" align="center"><?php if($_GET['o']!=6){ ?><a href="foro.php?o=6"><img src="../../images/common/edit_user.gif" title="<?=LANG_est_foro_alt ?>" width="24" height="24" border="0"></a><? }else{ ?><img src="../../images/common/edit_userU.gif" width="24" height="24" border="0"><?php } ?></td>
<td style="border:#FFFFFF solid 1px"  onMouseover="this.style.backgroundColor='#F3F7F8';this.style.border='#CBDDE2 solid 1px';"  onMouseout="this.style.backgroundColor='';this.style.border='#FFFFFF solid 1px';" width="14%" align="center"><?php if($_GET['o']!=7){ ?><a href="proy.php?o=7"><img src="../../images/common/proy.gif" title="<?=LANG_est_proy_alt ?>" width="24" height="24" border="0"></a><? }else{ ?><img src="../../images/common/proyU.gif" width="24" height="24" border="0"><?php } ?></td>

